DROP TABLE IF EXISTS datafeeds
DROP TABLE IF EXISTS parser_info
DROP TABLE IF EXISTS devices
DROP TABLE IF EXISTS datasources
DROP TABLE IF EXISTS topologies
DROP TABLE IF EXISTS topology_component_definitions
DROP TABLE IF EXISTS files
DROP TABLE IF EXISTS tag
DROP TABLE IF EXISTS tag_storable_mapping
DROP TABLE IF EXISTS sequence_table
DROP TABLE IF EXISTS topology_components
DROP TABLE IF EXISTS topology_sources
DROP TABLE IF EXISTS topology_source_stream_mapping
DROP TABLE IF EXISTS topology_sinks
DROP TABLE IF EXISTS topology_processors
DROP TABLE IF EXISTS topology_processor_stream_mapping
DROP TABLE IF EXISTS topology_edges
DROP TABLE IF EXISTS streaminfo
DROP TABLE IF EXISTS notifierinfos
DROP SEQUENCE IF EXISTS datasources_sequence
DROP SEQUENCE IF EXISTS datafeeds_sequence
DROP SEQUENCE IF EXISTS parser_info_sequence
DROP SEQUENCE IF EXISTS topologies_sequence
DROP SEQUENCE IF EXISTS topology_component_definitions_sequence
DROP SEQUENCE IF EXISTS tag_sequence
DROP SEQUENCE IF EXISTS files_sequence
DROP SEQUENCE IF EXISTS streaminfo_sequence
DROP SEQUENCE IF EXISTS notifierinfos_sequence
DROP SEQUENCE IF EXISTS topology_components_sequence
DROP SEQUENCE IF EXISTS topology_sources_sequence
DROP SEQUENCE IF EXISTS topology_sinks_sequence
DROP SEQUENCE IF EXISTS topology_processors_sequence
DROP SEQUENCE IF EXISTS topology_edges_sequence
