package org.apache.streamline.streams.catalog;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.apache.streamline.common.Schema;
import org.apache.streamline.storage.PrimaryKey;
import org.apache.streamline.storage.Storable;
import org.apache.streamline.storage.StorableKey;
import org.apache.streamline.streams.layout.component.TopologyDag;

import java.util.HashMap;
import java.util.Map;

/**
 * An Streamline topology that will be persisted in
 * storage layer. Generated by UI
 */
public class Topology implements Storable {

    public static final String NAME_SPACE = "topologies";
    public static final String ID = "id";
    public static final String VERSIONID = "versionId";
    public static final String NAME = "name";
    public static final String CONFIG = "config";
    public static final String TIMESTAMP = "timestamp";

    /**
     * Unique id identifying a topology. This is the composite primary key column.
     */
    private Long id;

    /**
     * Unique version id identifying a topology. This is the composite primary key column.
     */
    private Long versionId;

    /**
     * Human readable topology name; input from user from UI.
     */
    private String name;

    /**
     * Json string representing the topology configuration; generated by UI.
     */
    private String config;

    /**
     * Time at which this topology was created/updated.
     */
    private Long timestamp;

    /**
     * The topology DAG. This is internally generated and used for
     * deployment.
     */
    private TopologyDag topologyDag;

    public Topology() {
    }

    public Topology(Topology other) {
        setId(other.getId());
        setVersionId(other.getVersionId());
        setName(other.getName());
        setConfig(other.getConfig());
        setTimestamp(other.getTimestamp());
        // this will be re-generated during deployment.
        topologyDag = null;
    }

    @JsonIgnore
    public TopologyDag getTopologyDag() {
        return topologyDag;
    }

    @JsonIgnore
    public void setTopologyDag(TopologyDag topologyDag) {
        this.topologyDag = topologyDag;
    }

    @JsonIgnore
    public String getNameSpace () {
        return NAME_SPACE;
    }

    @JsonIgnore
    public Schema getSchema () {
        return Schema.of(
                new Schema.Field(ID, Schema.Type.LONG),
                new Schema.Field(VERSIONID, Schema.Type.LONG),
                new Schema.Field(NAME, Schema.Type.STRING),
                new Schema.Field(CONFIG, Schema.Type.STRING),
                new Schema.Field(TIMESTAMP, Schema.Type.LONG)
        );
    }

    @JsonIgnore
    public PrimaryKey getPrimaryKey () {
        Map<Schema.Field, Object> fieldToObjectMap = new HashMap<>();
        fieldToObjectMap.put(new Schema.Field(ID, Schema.Type.LONG), this.id);
        fieldToObjectMap.put(new Schema.Field(VERSIONID, Schema.Type.LONG), this.versionId);
        return new PrimaryKey(fieldToObjectMap);
    }

    @JsonIgnore
    public StorableKey getStorableKey () {
        return new StorableKey(getNameSpace(), getPrimaryKey());
    }

    public Map toMap () {
        Map<String, Object> map = new HashMap<>();
        map.put(ID, this.id);
        map.put(VERSIONID, this.versionId);
        map.put(NAME, this.name);
        map.put(CONFIG, this.config);
        map.put(TIMESTAMP, this.timestamp);
        return map;
    }

    public Topology fromMap (Map<String, Object> map) {
        this.id = (Long) map.get(ID);
        this.versionId = (Long) map.get(VERSIONID);
        this.name = (String) map.get(NAME);
        this.config = (String)  map.get(CONFIG);
        this.timestamp = (Long) map.get(TIMESTAMP);
        return this;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersionId() {
        return versionId;
    }

    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getConfig() {
        return config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    public Long getTimestamp () {
        return timestamp;
    }

    public void setTimestamp (Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "Topology{" +
                "id=" + id +
                ", versionId=" + versionId +
                ", name='" + name + '\'' +
                ", config='" + config + '\'' +
                ", timestamp=" + timestamp +
                ", topologyDag=" + topologyDag +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Topology topology = (Topology) o;

        if (id != null ? !id.equals(topology.id) : topology.id != null) return false;
        return versionId != null ? versionId.equals(topology.versionId) : topology.versionId == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (versionId != null ? versionId.hashCode() : 0);
        return result;
    }
}
