package com.hortonworks.iotas.catalog;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hortonworks.iotas.common.Schema;
import com.hortonworks.iotas.storage.PrimaryKey;
import com.hortonworks.iotas.storage.Storable;
import com.hortonworks.iotas.storage.StorableKey;

import java.util.HashMap;
import java.util.Map;

/**
 * An IoTaS topology that will be persisted in
 * storage layer. Generated by UI
 */
public class Topology implements Storable {

    public static final String NAME_SPACE = "topologies";
    public static final String ID = "id";
    public static final String NAME = "name";
    public static final String CONFIG = "config";
    public static final String TIMESTAMP = "timestamp";

    /**
     * Unique id identifying a topology. This is the primary key column.
     */
    private Long id;

    /**
     * Human readable topology name; input from user from UI.
     */
    private String name;

    /**
     * Json string representing the topology configuration; generated by UI.
     */
    private String config;

    /**
     * Time at which this topology was created/updated.
     */
    private Long timestamp;

    @JsonIgnore
    public String getNameSpace () {
        return NAME_SPACE;
    }

    @JsonIgnore
    public Schema getSchema () {
        return Schema.of(
                new Schema.Field(ID, Schema.Type.LONG),
                new Schema.Field(NAME, Schema.Type.STRING),
                new Schema.Field(CONFIG, Schema.Type.STRING),
                new Schema.Field(TIMESTAMP, Schema.Type.LONG)
        );
    }

    @JsonIgnore
    public PrimaryKey getPrimaryKey () {
        Map<Schema.Field, Object> fieldToObjectMap = new HashMap<Schema.Field, Object>();
        fieldToObjectMap.put(new Schema.Field(ID, Schema.Type.LONG),
                this.id);
        return new PrimaryKey(fieldToObjectMap);
    }

    @JsonIgnore
    public StorableKey getStorableKey () {
        return new StorableKey(getNameSpace(), getPrimaryKey());
    }

    public Map toMap () {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(ID, this.id);
        map.put(NAME, this.name);
        map.put(CONFIG, this.config);
        map.put(TIMESTAMP, this.timestamp);
        return map;
    }

    public Topology fromMap (Map<String, Object> map) {
        this.id = (Long) map.get(ID);
        this.name = (String) map.get(NAME);
        this.config = (String)  map.get(CONFIG);
        this.timestamp = (Long) map.get(TIMESTAMP);
        return this;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getConfig() {
        return config;
    }

    public void setConfig(String config) {
        this.config = config;
    }

    public Long getTimestamp () {
        return timestamp;
    }

    public void setTimestamp (Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString () {
        return "Topology{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", config='" + config + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }

    @Override
    public boolean equals (Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Topology that = (Topology) o;

        if (id != null ? !id.equals(that.id) : that.id != null)
            return false;
        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        if (config != null ? !config.equals(that.config) : that.config != null)
            return false;
        return true;
    }

    @Override
    public int hashCode () {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (config != null ? config.hashCode() : 0);
        return result;
    }


}
