DROP TABLE IF EXISTS datafeeds;
DROP TABLE IF EXISTS parser_info;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS datasources;
DROP TABLE IF EXISTS topologies;
DROP TABLE IF EXISTS topology_components;
DROP TABLE IF EXISTS files;
