DROP TABLE IF EXISTS parser_info
DROP TABLE IF EXISTS topology_versioninfos
DROP TABLE IF EXISTS topologies
DROP TABLE IF EXISTS topology_editor_metadata
DROP TABLE IF EXISTS topology_component_bundles
DROP TABLE IF EXISTS files
DROP TABLE IF EXISTS tag
DROP TABLE IF EXISTS tag_storable_mapping
DROP TABLE IF EXISTS sequence_table
DROP TABLE IF EXISTS topology_components
DROP TABLE IF EXISTS topology_sources
DROP TABLE IF EXISTS topology_source_stream_mapping
DROP TABLE IF EXISTS topology_sinks
DROP TABLE IF EXISTS topology_processors
DROP TABLE IF EXISTS topology_processor_stream_mapping
DROP TABLE IF EXISTS topology_edges
DROP TABLE IF EXISTS streaminfo
DROP TABLE IF EXISTS notifierinfos
DROP TABLE IF EXISTS ruleinfos
DROP TABLE IF EXISTS branchruleinfos
DROP TABLE IF EXISTS windowinfos
DROP TABLE IF EXISTS udfs
DROP TABLE IF EXISTS clusters
DROP TABLE IF EXISTS services
DROP TABLE IF EXISTS service_configurations
DROP TABLE IF EXISTS components
DROP TABLE IF EXISTS namespaces
DROP TABLE IF EXISTS namespace_service_cluster_mapping
DROP TABLE IF EXISTS dashboard
DROP TABLE IF EXISTS widget
DROP TABLE IF EXISTS datasource
DROP TABLE IF EXISTS widget_datasource_mapping
DROP SEQUENCE IF EXISTS parser_info_sequence
DROP SEQUENCE IF EXISTS topology_versioninfos_sequence
DROP SEQUENCE IF EXISTS topologies_sequence
DROP SEQUENCE IF EXISTS topology_component_bundles_sequence
DROP SEQUENCE IF EXISTS tag_sequence
DROP SEQUENCE IF EXISTS files_sequence
DROP SEQUENCE IF EXISTS streaminfo_sequence
DROP SEQUENCE IF EXISTS notifierinfos_sequence
DROP SEQUENCE IF EXISTS topology_components_sequence
DROP SEQUENCE IF EXISTS topology_sources_sequence
DROP SEQUENCE IF EXISTS topology_sinks_sequence
DROP SEQUENCE IF EXISTS topology_processors_sequence
DROP SEQUENCE IF EXISTS topology_edges_sequence
DROP SEQUENCE IF EXISTS ruleinfos_sequence
DROP SEQUENCE IF EXISTS windowinfos_sequence
DROP SEQUENCE IF EXISTS udfs_sequence
DROP SEQUENCE IF EXISTS clusters_sequence
DROP SEQUENCE IF EXISTS services_sequence
DROP SEQUENCE IF EXISTS service_configurations_sequence
DROP SEQUENCE IF EXISTS components_sequence
DROP SEQUENCE IF EXISTS namespaces_sequence
DROP SEQUENCE IF EXISTS dashboard_sequence
DROP SEQUENCE IF EXISTS widget_sequence
DROP SEQUENCE IF EXISTS datasource_sequence
