DROP TABLE IF EXISTS topology_version
DROP TABLE IF EXISTS topology
DROP TABLE IF EXISTS topology_editor_metadata
DROP TABLE IF EXISTS topology_component_bundle
DROP TABLE IF EXISTS file
DROP TABLE IF EXISTS tag
DROP TABLE IF EXISTS tag_storable_mapping
DROP TABLE IF EXISTS sequence_table
DROP TABLE IF EXISTS topology_component
DROP TABLE IF EXISTS topology_source
DROP TABLE IF EXISTS topology_source_stream_mapping
DROP TABLE IF EXISTS topology_sink
DROP TABLE IF EXISTS topology_processor
DROP TABLE IF EXISTS topology_processor_stream_mapping
DROP TABLE IF EXISTS topology_edge
DROP TABLE IF EXISTS topology_stream
DROP TABLE IF EXISTS notifier
DROP TABLE IF EXISTS topology_rule
DROP TABLE IF EXISTS topology_branchrule
DROP TABLE IF EXISTS topology_window
DROP TABLE IF EXISTS udf
DROP TABLE IF EXISTS cluster
DROP TABLE IF EXISTS service
DROP TABLE IF EXISTS service_configuration
DROP TABLE IF EXISTS component
DROP TABLE IF EXISTS namespace
DROP TABLE IF EXISTS namespace_service_cluster_mapping
DROP TABLE IF EXISTS dashboard
DROP TABLE IF EXISTS widget
DROP TABLE IF EXISTS datasource
DROP TABLE IF EXISTS widget_datasource_mapping
DROP TABLE IF EXISTS ml_model
DROP TABLE IF EXISTS topology_state
DROP SEQUENCE IF EXISTS topology_version_sequence
DROP SEQUENCE IF EXISTS topology_sequence
DROP SEQUENCE IF EXISTS topology_component_bundle_sequence
DROP SEQUENCE IF EXISTS tag_sequence
DROP SEQUENCE IF EXISTS file_sequence
DROP SEQUENCE IF EXISTS topology_stream_sequence
DROP SEQUENCE IF EXISTS notifier_sequence
DROP SEQUENCE IF EXISTS topology_component_sequence
DROP SEQUENCE IF EXISTS topology_source_sequence
DROP SEQUENCE IF EXISTS topology_sink_sequence
DROP SEQUENCE IF EXISTS topology_processor_sequence
DROP SEQUENCE IF EXISTS topology_edge_sequence
DROP SEQUENCE IF EXISTS topology_rule_sequence
DROP SEQUENCE IF EXISTS topology_window_sequence
DROP SEQUENCE IF EXISTS topology_branchrule_sequence
DROP SEQUENCE IF EXISTS udf_sequence
DROP SEQUENCE IF EXISTS cluster_sequence
DROP SEQUENCE IF EXISTS service_sequence
DROP SEQUENCE IF EXISTS service_configuration_sequence
DROP SEQUENCE IF EXISTS component_sequence
DROP SEQUENCE IF EXISTS namespace_sequence
DROP SEQUENCE IF EXISTS dashboard_sequence
DROP SEQUENCE IF EXISTS widget_sequence
DROP SEQUENCE IF EXISTS datasource_sequence
DROP SEQUENCE IF EXISTS ml_model_sequence
DROP SEQUENCE IF EXISTS topology_state_sequence
